//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.BoletaVendedorClienteServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletaVendedorCliente", Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    [System.SerializableAttribute()]
    public partial class BoletaVendedorCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteNombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteRutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumeroBoletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioVendedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteNombreCompleto {
            get {
                return this.ClienteNombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteNombreCompletoField, value) != true)) {
                    this.ClienteNombreCompletoField = value;
                    this.RaisePropertyChanged("ClienteNombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteRut {
            get {
                return this.ClienteRutField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteRutField, value) != true)) {
                    this.ClienteRutField = value;
                    this.RaisePropertyChanged("ClienteRut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumeroBoleta {
            get {
                return this.NumeroBoletaField;
            }
            set {
                if ((this.NumeroBoletaField.Equals(value) != true)) {
                    this.NumeroBoletaField = value;
                    this.RaisePropertyChanged("NumeroBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioVendedor {
            get {
                return this.UsuarioVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioVendedorField, value) != true)) {
                    this.UsuarioVendedorField = value;
                    this.RaisePropertyChanged("UsuarioVendedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoletaVendedorClienteServ.IServicioBoletaVendedorCliente")]
    public interface IServicioBoletaVendedorCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBoletaVendedorCliente/ListarBoletaVendedorCliente", ReplyAction="http://tempuri.org/IServicioBoletaVendedorCliente/ListarBoletaVendedorClienteResp" +
            "onse")]
        CapaWeb.BoletaVendedorClienteServ.BoletaVendedorCliente[] ListarBoletaVendedorCliente(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBoletaVendedorCliente/ListarBoletaVendedorCliente", ReplyAction="http://tempuri.org/IServicioBoletaVendedorCliente/ListarBoletaVendedorClienteResp" +
            "onse")]
        System.Threading.Tasks.Task<CapaWeb.BoletaVendedorClienteServ.BoletaVendedorCliente[]> ListarBoletaVendedorClienteAsync(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioBoletaVendedorClienteChannel : CapaWeb.BoletaVendedorClienteServ.IServicioBoletaVendedorCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBoletaVendedorClienteClient : System.ServiceModel.ClientBase<CapaWeb.BoletaVendedorClienteServ.IServicioBoletaVendedorCliente>, CapaWeb.BoletaVendedorClienteServ.IServicioBoletaVendedorCliente {
        
        public ServicioBoletaVendedorClienteClient() {
        }
        
        public ServicioBoletaVendedorClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBoletaVendedorClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBoletaVendedorClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBoletaVendedorClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaWeb.BoletaVendedorClienteServ.BoletaVendedorCliente[] ListarBoletaVendedorCliente(string usuario) {
            return base.Channel.ListarBoletaVendedorCliente(usuario);
        }
        
        public System.Threading.Tasks.Task<CapaWeb.BoletaVendedorClienteServ.BoletaVendedorCliente[]> ListarBoletaVendedorClienteAsync(string usuario) {
            return base.Channel.ListarBoletaVendedorClienteAsync(usuario);
        }
    }
}
